config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :article_catalogs
  resources :article_categories, path: "go"
  resources :sites, path: "site"
  # get 'quickrank_performances/index'

  # get 'quickrank_portfolios/index'

  # get 'quickrank_snapshots/index'

  get :search, to: "pages#search"

  resources :fundcompany, path: 'company', only: [] do
    collection do
      get :star
      get :best_return
      get :performance
    end
  end

  resources :quickrank do
    collection do
      # get ":date_history", to: "quickrank#date_history", as: :date_history

      get :performance, to: "quickrank_performances#index"
      get :portfolio, to: "quickrank_portfolios#index"
      get :snapshot, to: "quickrank_snapshots#index"
      get :history, to: "fund_rankings#index"

      get :search
      post :search
    end
  end

  get "quickrank/history/search", to: "fund_rankings#search"

  resources :tags, path: 'tag', only: [:index, :show]

  resources :fund_yields
  resources :task_logs
  resources :fund_rankings
  resources :stocks
  resources :quotes


  resources :fund_fen_hongs do
    collection do
      get :list
    end
  end

  resources :fund_chai_fens


  mount RedactorRails::Engine => '/redactor_rails'

  resources :articles do
    resources :comments

    resources :agreement_articles, only: [:create, :destroy]
  end

  resources :index_reports, only: :index do
    collection do
      get ":catalog_slug", to: "index_reports#catalog", as: :catalog_slug
      get ":catalog_slug/:category_slug", to: "index_reports#category", as: :catalog_slug_category_slug
    end
  end

  resources :index_reports, path: 'index_report'

  # resources :index_catalogs
  # resources :index_categories

  get 'user_favor_comment/create'

  get 'user_favor_comment/destroy'

  get 'pages/:name', to: "pages#show"

  mount RuCaptcha::Engine => "/rucaptcha"

  authenticate :user, lambda { |u| u.is_admin? } do
    namespace :panel do
      resources :stats

      resources :episodes

      resources :categories do
        member do
          post :create_projects
        end

        collection do
          get :search
        end
      end
      resources :catalogs do
        collection do
          get :search
        end
      end
      resources :projects do
        collection do
          get :search
          get :magic_search
          post :search_result
        end
      end
    end
  end

  resources :episodes do
    collection do
      # get 'today-recommends', to: "episodes#today", as: :today
      get :today
    end
  end
  # resources :developers, only: [:show]
  resources :developers, path: "manager"

  resources :net_worths

  resources :user_recommend_projects, only: [:create, :destroy]
  resources :user_star_projects, only: [:create, :destroy]
  resources :comments

  authenticate :user, lambda { |u| u.is_admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :projects, path: "fund" do
    member do
      get :popularity, to: "repos#popularity"

      get :star, to: "repos#star"
      get :recommend, to: "repos#recommend"

      get :calculus, to: "project_arithmetic#calculus"

      get :managers

      get :distribute
    end

    resource :recommend_project, only: [:new, :create] do
      member do
        post 'add_to_episode/:episode_id', action: :add, as: :add_to
        delete 'remove_from_episode/:episode_id', action: :remove, as: :remove_from
      end
    end

    post :star, to: "user_star_projects#create"
    post :recommend, to: "user_recommend_projects#create"

    delete :star, to: "user_star_projects#destroy"
    delete :recommend, to: "user_recommend_projects#destroy"

    collection do
      get :search, to: "project_search#index"
      get :ruby_gems, to: "project_search#index", type: 'gemspec', as: :search_gem
      get :php_packages, to: "project_search#index", type: 'package', as: :search_package
      get :swift_pods, to: "project_search#index", type: 'pod', as: :search_pod
    end

    resources :comments
  end

  resources :developer_projects, only: [:destroy]

  get ':author/:name/star', to: "repos#star", as: :star_repo
  get ':author/:name/recommend', to: "repos#recommend", as: :recommend_repo
  get ':author/:name/popularity', to: "repos#popularity", as: :popularity_repo


  resources :catalogs, path: "company" do
    resources :catalog_developers, path: 'managers', only: [:index]
  end
  resources :categories

  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'ruby-gems', to: "catalogs#rails", as: :rails
  get 'Ruby-Gems', to: "catalogs#rails"
  get 'gems', to: "catalogs#rails"
  get 'swift-pods', to: "catalogs#swift", as: :swift
  get 'Swift-Pods', to: "catalogs#swift"
  get 'pods', to: "catalogs#swift"
  get 'PHP-Packages', to: "catalogs#laravel", as: :laravel
  get 'packages', to: "catalogs#laravel"

  get 'account', to: "users#account"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
  :passwords => "users/passwords", :registrations => "users/registrations",
  :sessions => "users/sessions" }

  resources :users, path: "u" do
    # get :id
  end

  get 'projects/:code-:slug', to: "projects#repo", as: :repo

  # get ':name', to: "developers#show", as: :show_developer
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :get_today_recommend_projects, only: [:index]
  layout 'one_page'

  def index
    @tags = CustomTag.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_catalog.html.erb
  <li class="list-group-item catalog-item">
    <span class="badge badge-count"><%= catalog.online_categories_count %></span>
    <%= link_to catalog.name, catalog_path(catalog) %>
  </li>

app/views/home/_old_index_content.html.erb
<!-- <div class="col-md-12 content" style="margin-top: 20px;padding-top: 20px;"> -->
  <div class="col-md-6 no-padding-left xs-no-padding">
    <div class="panel panel-default">
      <div class="panel-heading panel-title">
        <h2 class="top-catalog">
          <%= link_to rails_path do %>
            <%= Catalog::TOP_PLURAL['gemspec'] %>
          <% end %>

          <small class="pull-right">
            <%#= RailsCatalog.online.count %>
          </small>
        </h2>

      </div>
      <!-- <div class="panel-body"> -->
        <ul class="list-group">
          <%= render partial: "home/catalog", as: :catalog, collection: RailsCatalog.online.includes(:categories) %>
        </ul>
      <!-- </div> -->
    </div>
  </div>

  <!-- <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="top-catalog">
          <%#= link_to laravel_path do %>
            Packages
          <%# end %>
        </h2>

        <section class="pull-right">
          <%#= LaravelCatalog.count %>
        </section>
      </div>

      <div class="panel-body"> -->
        <!-- <ul class="list-group"> -->
          <%#= render partial: "home/catalog", as: :catalog, collection: LaravelCatalog.all.includes(:categories) %>
        <!-- </ul> -->
      <!-- </div>
    </div>
  </div> -->

  <div class="col-md-6 no-padding-right xs-no-padding">
    <div class="panel panel-default">
      <div class="panel-heading panel-title">
        <h2 class="top-catalog">
          <%= link_to swift_path do %>
            <%= Catalog::TOP_PLURAL['pod'] %>
          <% end %>

          <small class="pull-right">
            <%#= SwiftCatalog.online.count %>
          </small>
        </h2>

      </div>

      <!-- <div class="panel-body"> -->
        <ul class="list-group">
          <%#= render partial: "home/catalog", as: :catalog, collection: SwiftCatalog.online.includes(:categories) %>
        </ul>
      <!-- </div> -->
    </div>
  </div>
<!-- </div> -->

app/views/home/_project.html.erb
<div class="col-md-4 recommend-item">
  <h3>
    <%= link_to repo_path(project.repo_params) do %>
      <%= project.show_name %>
    <% end %>
  </h3>

  <%= link_to repo_path(project.repo_params), class: "wrap-description" do %>
    <%= simple_format project.description, {class: "text-muted"} %>
  <% end %>
</div>

app/views/home/_tag.html.erb
<dt class="col-md-1 col-xs-6 no-padding">
   <%= link_to tag_path(tag), target: "_blank" do %>
    <%= tag.name %>
  <% end %>
</dt>

<dd class="col-md-1 col-xs-6">
 <span class="">
   <%= tag.taggings_count %>
 </span>
</dd>

app/views/home/index.html.erb
<% set_meta_tags description: Settings.website.slogan %>

<% content_for :content_css_link_yield do %>
  <%= stylesheet_link_tag 'home' %>
<% end %>

<% content_for :prefix do %>
  <!-- <div class="container bg-color-white prefix">
    <h1 class="slogan">
      <%#= image_tag "demo-WechatIMG5.jpeg" %>
      <%#= Settings.website.slogan %>
    </h1>
  </div> -->
<% end %>

<div class="container content">
  <div class="title-v1">
    <h2>
      <%= Settings.website.slogan %>
    </h2>

    <p>
      多年基金实战经验，经历牛熊洗礼，我们更<strong>专业</strong>，移动互联时代，结合多年经验加技术，我们更<strong>现代</strong>，<br>
      用数据说话，用业绩证明，我们是您的朋友，我们是您<strong>可靠</strong>选择。
    </p>
  </div>

  <div class="row">
    <div class="col-md-6 content-boxes-v3 margin-bottom-40">
      <div class="clearfix margin-bottom-30">
        <i class="icon-custom icon-md rounded-x icon-bg-u icon-line icon-trophy fa fa-connectdevelop"></i>
        <div class="content-boxes-in-v3">
          <h2 class="heading-sm">专业</h2>
          <p>投资指数基金，是一般人做投资的最好选择，会超过大部分的投资人，从过往历史上也可以得出这个结论，过去20年傻傻的拿着指数基金的回报，远远超过90% 的专业投资人。</p>
        </div>
      </div>
      <div class="clearfix margin-bottom-30">
        <i class="icon-custom icon-md rounded-x icon-bg-u icon-line icon-directions fa fa-cc-mastercard"></i>
        <div class="content-boxes-in-v3">
          <h2 class="heading-sm">现代</h2>
          <p>互联网企业与基金公司跨界合作，抓住人们不同用途的闲置资金，进行细分市场的短期理财。这些产品降低了基金投资门槛，申购赎回操作方便，具备较好的流动性特征。</p>
        </div>
      </div>
      <div class="clearfix margin-bottom-30">
        <i class="icon-custom icon-md rounded-x icon-bg-u icon-line icon-diamond fa fa-line-chart"></i>
        <div class="content-boxes-in-v3">
          <h2 class="heading-sm">可靠</h2>
          <p>营运各种基金资产。投资者投资于基金，犹如聘请一个专业化的投资顾问，既省力又安全可靠，且可获得较高的收益。</p>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <%= image_tag "pexels-photo-159888.jpg", class: "img-responsive", alt: "基金工具官网" %>
    </div>
  </div>
</div>



<% if @episode.present? %>
  <!-- <div class="col-md-12"> -->
  <div class="panel panel-default clearfix">
    <div class="panel-heading">
      <%= render "episodes/recommend_title", episode: @episode %>
    </div>

    <div class="panel-body">

      <div class="recommend-projects">
        <div class="row">
          <%= render partial: "home/project", collection: @recommend_gems, as: :project %>
        </div>

        <!-- <hr>

        <div class="row">
          <%#= render partial: "home/project", collection: @packages, as: :project %>
        </div> -->

        <hr>

        <div class="row">
          <%= render partial: "home/project", collection: @recommend_pods, as: :project %>
        </div>
      </div>
    </div>
  </div>
  <!-- </div> -->
<% end %>

<div class="container">
  <div class="panel panel-default clearfix">
    <div class="panel-heading">股票型基金</div>
    <div class="panel-body">
      股票基金亦称股票型基金，指的是投资于股票市场的基金。证券基金的种类很多。目前我国除股票基金外，还有债券基金、股票债券混合基金、货币市场基金等。
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">混合型基金</div>
    <div class="panel-body">
      混合型基金 [Blend fund, hybrid fund]是在投资组合中既有成长型股票、收益型股票，又有债券等固定收益投资的共同基金。
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">债券型基金</div>
    <div class="panel-body">
      (Bond Fund)以国债、金融债等固定收益类金融工具为主要投资对象的基金称为债券型基金，因为其投资的产品收益比较稳定，又被称为“固定收益基金”。
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">指数型基金</div>
    <div class="panel-body">
      指数基金(Index Fund)，顾名思义就是以特定指数（如沪深300指数、标普500指数、纳斯达克100指数、日经225指数等）为标的指数，并以该指数的成份股为投资对象，通过购买该指数的全部或部分成份股构建投资组合，以追踪标的指数表现的基金产品。
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">ETF联接基金</div>
    <div class="panel-body">
      ETF联接基金是指将其绝大部分基金财产投资于跟踪同一标的指数的ETF基金，也就是说是投资于ETF基金的基金(简称目标ETF)，密切跟踪标的指数表现，追求跟踪偏离度和跟踪误差最小化，采用开放式运作方式的基金。
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">QDII</div>
    <div class="panel-body">
      QDII，是“Qualified Domestic Institutional Investor”的首字缩写，合格境内机构投资者，是指在人民币资本项下不可兑换、资本市场未开放条件下，在一国境内设立，经该国有关部门批准，有控制地，允许境内机构投资境外资本市场的股票、债券等有价证券投资业务的一项制度安排。
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">LOF基金</div>
    <div class="panel-body">
      LOF基金，英文全称是"Listed Open-Ended Fund"，汉语称为"上市型开放式基金"。
    </div>
  </div>

  <% cache @tags.ids do %>
    <div class="panel panel-default">
      <div class="panel-heading">全部基金分类</div>

      <div class="panel-body">
        <% @tags.each_slice(6) do |tags| %>

          <dl class="clearfix home-tags">
            <%= render partial: "home/tag", collection: tags %>
          </dl>

        <% end %>
      </div>
    </div>
  <% end %>
</div>


<% content_for :postfix do %>
  <div class="container content">
    <div class="bg-color-white postfix">
      <%= render 'quickrank/nav' %>
    </div>
  </div>
<% end %>