config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :article_catalogs
  resources :article_categories, path: "go"
  resources :sites, path: "site"
  # get 'quickrank_performances/index'

  # get 'quickrank_portfolios/index'

  # get 'quickrank_snapshots/index'

  get :search, to: "pages#search"

  resources :fundcompany, path: 'company', only: [] do
    collection do
      get :star
      get :best_return
      get :performance
    end
  end

  resources :quickrank do
    collection do
      # get ":date_history", to: "quickrank#date_history", as: :date_history

      get :performance, to: "quickrank_performances#index"
      get :portfolio, to: "quickrank_portfolios#index"
      get :snapshot, to: "quickrank_snapshots#index"
      get :history, to: "fund_rankings#index"

      get :search
      post :search
    end
  end

  get "quickrank/history/search", to: "fund_rankings#search"

  resources :tags, path: 'tag', only: [:index, :show]

  resources :fund_yields
  resources :task_logs
  resources :fund_rankings
  resources :stocks
  resources :quotes


  resources :fund_fen_hongs do
    collection do
      get :list
    end
  end

  resources :fund_chai_fens


  mount RedactorRails::Engine => '/redactor_rails'

  resources :articles do
    resources :comments

    resources :agreement_articles, only: [:create, :destroy]
  end

  resources :index_reports, only: :index do
    collection do
      get ":catalog_slug", to: "index_reports#catalog", as: :catalog_slug
      get ":catalog_slug/:category_slug", to: "index_reports#category", as: :catalog_slug_category_slug
    end
  end

  resources :index_reports, path: 'index_report'

  # resources :index_catalogs
  # resources :index_categories

  get 'user_favor_comment/create'

  get 'user_favor_comment/destroy'

  get 'pages/:name', to: "pages#show"

  mount RuCaptcha::Engine => "/rucaptcha"

  authenticate :user, lambda { |u| u.is_admin? } do
    namespace :panel do
      resources :stats

      resources :episodes

      resources :categories do
        member do
          post :create_projects
        end

        collection do
          get :search
        end
      end
      resources :catalogs do
        collection do
          get :search
        end
      end
      resources :projects do
        collection do
          get :search
          get :magic_search
          post :search_result
        end
      end
    end
  end

  resources :episodes do
    collection do
      # get 'today-recommends', to: "episodes#today", as: :today
      get :today
    end
  end
  # resources :developers, only: [:show]
  resources :developers, path: "manager"

  resources :net_worths

  resources :user_recommend_projects, only: [:create, :destroy]
  resources :user_star_projects, only: [:create, :destroy]
  resources :comments

  authenticate :user, lambda { |u| u.is_admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :projects, path: "fund" do
    member do
      get :popularity, to: "repos#popularity"

      get :star, to: "repos#star"
      get :recommend, to: "repos#recommend"

      get :calculus, to: "project_arithmetic#calculus"

      get :managers

      get :distribute
    end

    resource :recommend_project, only: [:new, :create] do
      member do
        post 'add_to_episode/:episode_id', action: :add, as: :add_to
        delete 'remove_from_episode/:episode_id', action: :remove, as: :remove_from
      end
    end

    post :star, to: "user_star_projects#create"
    post :recommend, to: "user_recommend_projects#create"

    delete :star, to: "user_star_projects#destroy"
    delete :recommend, to: "user_recommend_projects#destroy"

    collection do
      get :search, to: "project_search#index"
      get :ruby_gems, to: "project_search#index", type: 'gemspec', as: :search_gem
      get :php_packages, to: "project_search#index", type: 'package', as: :search_package
      get :swift_pods, to: "project_search#index", type: 'pod', as: :search_pod
    end

    resources :comments
  end

  resources :developer_projects, only: [:destroy]

  get ':author/:name/star', to: "repos#star", as: :star_repo
  get ':author/:name/recommend', to: "repos#recommend", as: :recommend_repo
  get ':author/:name/popularity', to: "repos#popularity", as: :popularity_repo


  resources :catalogs, path: "company" do
    resources :catalog_developers, path: 'managers', only: [:index]
  end
  resources :categories

  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'ruby-gems', to: "catalogs#rails", as: :rails
  get 'Ruby-Gems', to: "catalogs#rails"
  get 'gems', to: "catalogs#rails"
  get 'swift-pods', to: "catalogs#swift", as: :swift
  get 'Swift-Pods', to: "catalogs#swift"
  get 'pods', to: "catalogs#swift"
  get 'PHP-Packages', to: "catalogs#laravel", as: :laravel
  get 'packages', to: "catalogs#laravel"

  get 'account', to: "users#account"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
  :passwords => "users/passwords", :registrations => "users/registrations",
  :sessions => "users/sessions" }

  resources :users, path: "u" do
    # get :id
  end

  get 'projects/:code-:slug', to: "projects#repo", as: :repo

  # get ':name', to: "developers#show", as: :show_developer
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id                    :integer          not null, primary key
#  name                  :string(255)
#  slug                  :string(255)
#  catalog_id            :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  user_id               :integer
#  projects_count        :integer          default(0)
#  online_projects_count :integer          default(0), not null
#  status                :integer          default("online")
#

class Category < ApplicationRecord
  # Associations
  belongs_to :catalog #, counter_cache: true
  counter_culture :catalog
  counter_culture :catalog, :column_name => proc {|model| model.online? ? 'online_categories_count' : nil }

  has_many :projects
  # END


  # Callbacks
  before_create :set_slug
  # END

  # Rails class methods
  enum status: { online: 0, offline: 11, reviewed: 22}
  # END

  def self.no_online_projects_so_offline
    Category.where(online_projects_count: 0).update_all(status: Category.statuses['offline'])
  end

  def self.nil_catalog_so_offline
    Category.where(catalog_id: nil).update_all(status: Category.statuses['offline'])
  end

  def self.set_categories
    ["Active Record DB Adapters",
    "Active Record Default Values",
    "Active Record Enumerations",
    "Active Record Index Assistants",
    "Active Record Named Scopes",
    "Active Record Nesting",
    "Active Record Sharding",
    "Active Record Soft Delete",
    "Active Record Sortables",
    "Active Record User Stamping",
    "Active Record Value Cleanup",
    "Active Record Versioning",
    "Pagination",
    "Rails Comments",
    "Rails DB Bootstrapping",
    "Rails Ratings",
    "Rails Search",
    "Rails Tagging"].each do |category|
      next if category.blank?
      catalog = Catalog.find_by(name: "Active Record Plugins")

      next if catalog.blank?

      catalog.categories.create(name: category,
        slug: Pinyin.t(category, splitter: "_"))
    end

    ["Background Jobs",
    "Daemonizing",
    "Daemon Management",
    "Scheduling"].each do |category|
      next if category.blank?
      catalog = Catalog.find_by(name: "Background Processing")

      next if catalog.blank?

      catalog.categories.create(name: category,
        slug: Pinyin.t(category, splitter: "_"))
    end
  end

  def self.delay_get_projects(category_id)
    category = Category.find(category_id)

    category_name = category.slug
    category_name_downcase = category.slug.try(:downcase)

    url = "https://www.ruby-toolbox.com/categories/#{category_name}"
    url_downcase = "https://www.ruby-toolbox.com/categories/#{category_name_downcase}"

    unless url == url_downcase
      delay = rand(1..3600)
      self.delay_for(delay).ruby_toolbox(url_downcase, category.id)
    end

    delay = rand(1..3600)
    self.delay_for(delay).ruby_toolbox(url, category.id)
  end

  def self.ruby_toolbox(url, category_id)
    doc = ::Nokogiri::HTML(` curl "#{url}" `)

    if doc.present?
      source_codes = doc.css("a.source_code")

      return if source_codes.blank?

      source_codes.each do |source_code|
        github_url = source_code.attributes['href'].value

        if github_url =~ /github\.com/
          delay = rand(1..3600)
          Project.delay_for(delay).get_and_create_gem_project_from(github_url, category_id)
        end
      end
    end
  end

  def set_slug
    self.slug = Pinyin.t(self.name, splitter: '_')
  end

  def to_param
    "#{self.id}-#{self.slug}"
  end

  def full_name
    "#{self.catalog.try(:type)} - #{self.catalog.try(:name)} - #{self.name}"
  end

  def meta_title_name
    if self.catalog_id.present?
      "#{self.name} - #{self.catalog.try(:human_type)}"
    else
      self.name
    end
  end

  def self.detect_and_set_online
    self.joins(:catalog).offline.where("categories.online_projects_count > ?", 0).update_all(status: Category.statuses['online'])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :edit, :destroy]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.online.includes(:catalog)
  end

  # GET /categories/1
  def show
    @projects = @category.projects.online.order(popularity: :desc).includes(:github_info)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /categories/1
  def update
    authorize! :update, @category

    respond_to do |format|
      if @category.update(category_params.merge(user_id: current_user.id))
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  def destroy
    authorize! :destroy, @category

    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :slug, :catalog_id)
    end
end

app/controllers/panel/categories_controller.rb
class Panel::CategoriesController < Panel::PanelController
  before_action :set_panel_category, only: [:show, :edit, :update, :destroy, :create_projects]

  def create_projects
    if params[:projects_source_code].blank?
      return false
    end

    projects_source_code = params[:projects_source_code].split(/\r\n|\s/).delete_if{|x| x.blank? || !(x =~ /github\.com/)}

    catalog = @panel_category.catalog
    if catalog.present?
      identity = catalog.project_identity
    end

    projects_source_code.each do |link|
      delay = rand(1..60)
      Project.delay_for(delay).get_and_create_gem_project_from_option({'source_code' => link, 'identity' => identity, category_id: @panel_category.id})
    end

    redirect_to panel_category_url(@panel_category), notice: '正在抓取项目到此类目，请稍等。'
  end

  def search
    @panel_categories = ::Category.all.order(id: :desc).includes(:catalog).page(params[:page])

    if params[:top_catalog].present?
      @panel_categories = @panel_categories.joins(:catalog).where(catalogs: {type: params[:top_catalog]})
    end

    if params[:name].present?
      @panel_categories = @panel_categories.joins(:catalog).where("catalogs.name LIKE ? OR categories.name LIKE ?", "%#{params[:name]}%", "%#{params[:name]}%")
    end

    if params[:status].present?
      @panel_categories = @panel_categories.where(status: params[:status])
    end

    if params[:projects_count].present?
      @panel_categories = @panel_categories.where(projects_count: params[:projects_count])
    end

    render :index
  end

  # GET /panel/categories
  def index
    @panel_categories = ::Category.all.order(id: :desc).includes(:catalog).page(params[:page])
  end

  # GET /panel/categories/1
  def show
    @projects = @panel_category.projects.order(popularity: :desc).page(params[:page])
  end

  # GET /panel/categories/new
  def new
    @panel_category = ::Category.new
  end

  # GET /panel/categories/1/edit
  def edit
  end

  # POST /panel/categories
  def create
    @panel_category = ::Category.new(panel_category_params)
    respond_to do |format|
      if @panel_category.save
        format.html { redirect_to edit_panel_category_url(@panel_category), notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /panel/categories/1
  def update
    respond_to do |format|
      if @panel_category.update(panel_category_params)
        format.html { redirect_to edit_panel_category_url(@panel_category), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /panel/categories/1
  def destroy
    @panel_category.destroy
    respond_to do |format|
      format.html { redirect_to panel_categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel_category
      @panel_category = ::Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panel_category_params
      params.fetch(:category, {}).permit(:name, :status, :slug, :catalog_id)
    end
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="control-group">
    <%= f.label :slug %>
    <%= f.text_field :slug, class: "form-control" %>
  </div>

  <div class="control-group">
    <%= f.label :catalog_id %>

    <% catalog = category.catalog %>

    <% if catalog.present? %>
      <% catalogs = catalog.class.online %>
    <% else %>
      <% catalogs = Catalog.online %>
    <% end %>

    <%= f.select :catalog_id, catalogs.collect { |p| [ p.name, p.id ] }, {include_blank: true}, {class: "form-control"} %>
  </div>

  <br>

  <div class="actions">
    <%= f.submit "提交", class: "btn btn-primary" %>
  </div>
<% end %>

<br>

app/views/categories/_list_item.html.erb
<li class="list-group-item catalog-item">
  <span class="badge badge-count">
    <%= category.online_projects_count %>
  </span>

  <%= link_to category.name, category %>
</li>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% set_meta_tags title: "Categories" %>


<div class="panel panel-default">


  <div class="panel-heading">
    <h1>
      Categories
      <small>
        <%= link_to 'New Category', new_category_path %>
      </small>
    </h1>
  </div>

  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Slug</th>
          <th>Catalog</th>
          <th>Projects</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td>
              <%= link_to category do %>
                <%= category.name %>
              <% end %>
            </td>
            <td><%= category.slug %></td>
            <td>
              <%= category.catalog.name %>
            </td>

            <td>
              <%= category.online_projects_count %>
            </td>

            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<%#= link_to 'New Category', new_category_path %>

app/views/categories/language.html.erb
<div class="row">
  <div class="col-md-9">
    <ul>
      <% @categories.each do |category| %>
        <li><%= category.name %></li>

        <ul>
          <% category.packages.each do |package| %>
            <li>
              <%= link_to package.name, package %>
            </li>
          <% end %>
        </ul>
      <% end %>

    </ul>
  </div>

  <div class="col-md-3">
    col-md-3
  </div>
</div>

app/views/categories/new.html.erb
<div class="col-md-12">
  <h1>New Category</h1>

  <%= render 'form', category: @category %>

</div>

app/views/categories/show.html.erb
<% set_meta_tags title: @category.meta_title_name %>

<% content_for :content_css_link_yield do %>
  <%= stylesheet_link_tag 'categories' %>
<% end %>

<ol class="breadcrumb catalog-category-etc">
  <li class="normal">
    <% url = @category.catalog.type.downcase.gsub(/catalog$/, '_path') %>

    <%= link_to eval(url) do %>
      <%= @category.catalog.human_supercatalog_name %>
    <% end %>
  </li>

  <li class="normal">
    <%= link_to catalog_path(@category.catalog) do %>
      <%= @category.catalog.name %>
    <% end %>
  </li>

  <li class="active"><%= @category.name %></li>
</ol>


<% if @category.present? %>
  <div class="panel panel-default popular-projects">
    <%= render "projects/popular_item" %>
  </div>
<% end %>


<div class="panel panel-default">
  <div class="panel-heading">
    本类目下共有 <%= @projects.size %> 个项目
  </div>

  <div class="panel-body">
    <% if @projects.blank? %>
      <div class="text-center text-muted">
        没有搜索到结果
      </div>
    <% else %>
      <ul class="media-list">
        <%= render partial: "projects/media_list_item", collection: @projects, as: :project %>
      </ul>
    <% end %>
  </div>
</div>