config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :article_catalogs
  resources :article_categories, path: "go"
  resources :sites, path: "site"
  # get 'quickrank_performances/index'

  # get 'quickrank_portfolios/index'

  # get 'quickrank_snapshots/index'

  get :search, to: "pages#search"

  resources :fundcompany, path: 'company', only: [] do
    collection do
      get :star
      get :best_return
      get :performance
    end
  end

  resources :quickrank do
    collection do
      # get ":date_history", to: "quickrank#date_history", as: :date_history

      get :performance, to: "quickrank_performances#index"
      get :portfolio, to: "quickrank_portfolios#index"
      get :snapshot, to: "quickrank_snapshots#index"
      get :history, to: "fund_rankings#index"

      get :search
      post :search
    end
  end

  get "quickrank/history/search", to: "fund_rankings#search"

  resources :tags, path: 'tag', only: [:index, :show]

  resources :fund_yields
  resources :task_logs
  resources :fund_rankings
  resources :stocks
  resources :quotes


  resources :fund_fen_hongs do
    collection do
      get :list
    end
  end

  resources :fund_chai_fens


  mount RedactorRails::Engine => '/redactor_rails'

  resources :articles do
    resources :comments

    resources :agreement_articles, only: [:create, :destroy]
  end

  resources :index_reports, only: :index do
    collection do
      get ":catalog_slug", to: "index_reports#catalog", as: :catalog_slug
      get ":catalog_slug/:category_slug", to: "index_reports#category", as: :catalog_slug_category_slug
    end
  end

  resources :index_reports, path: 'index_report'

  # resources :index_catalogs
  # resources :index_categories

  get 'user_favor_comment/create'

  get 'user_favor_comment/destroy'

  get 'pages/:name', to: "pages#show"

  mount RuCaptcha::Engine => "/rucaptcha"

  authenticate :user, lambda { |u| u.is_admin? } do
    namespace :panel do
      resources :stats

      resources :episodes

      resources :categories do
        member do
          post :create_projects
        end

        collection do
          get :search
        end
      end
      resources :catalogs do
        collection do
          get :search
        end
      end
      resources :projects do
        collection do
          get :search
          get :magic_search
          post :search_result
        end
      end
    end
  end

  resources :episodes do
    collection do
      # get 'today-recommends', to: "episodes#today", as: :today
      get :today
    end
  end
  # resources :developers, only: [:show]
  resources :developers, path: "manager"

  resources :net_worths

  resources :user_recommend_projects, only: [:create, :destroy]
  resources :user_star_projects, only: [:create, :destroy]
  resources :comments

  authenticate :user, lambda { |u| u.is_admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :projects, path: "fund" do
    member do
      get :popularity, to: "repos#popularity"

      get :star, to: "repos#star"
      get :recommend, to: "repos#recommend"

      get :calculus, to: "project_arithmetic#calculus"

      get :managers

      get :distribute
    end

    resource :recommend_project, only: [:new, :create] do
      member do
        post 'add_to_episode/:episode_id', action: :add, as: :add_to
        delete 'remove_from_episode/:episode_id', action: :remove, as: :remove_from
      end
    end

    post :star, to: "user_star_projects#create"
    post :recommend, to: "user_recommend_projects#create"

    delete :star, to: "user_star_projects#destroy"
    delete :recommend, to: "user_recommend_projects#destroy"

    collection do
      get :search, to: "project_search#index"
      get :ruby_gems, to: "project_search#index", type: 'gemspec', as: :search_gem
      get :php_packages, to: "project_search#index", type: 'package', as: :search_package
      get :swift_pods, to: "project_search#index", type: 'pod', as: :search_pod
    end

    resources :comments
  end

  resources :developer_projects, only: [:destroy]

  get ':author/:name/star', to: "repos#star", as: :star_repo
  get ':author/:name/recommend', to: "repos#recommend", as: :recommend_repo
  get ':author/:name/popularity', to: "repos#popularity", as: :popularity_repo


  resources :catalogs, path: "company" do
    resources :catalog_developers, path: 'managers', only: [:index]
  end
  resources :categories

  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'ruby-gems', to: "catalogs#rails", as: :rails
  get 'Ruby-Gems', to: "catalogs#rails"
  get 'gems', to: "catalogs#rails"
  get 'swift-pods', to: "catalogs#swift", as: :swift
  get 'Swift-Pods', to: "catalogs#swift"
  get 'pods', to: "catalogs#swift"
  get 'PHP-Packages', to: "catalogs#laravel", as: :laravel
  get 'packages', to: "catalogs#laravel"

  get 'account', to: "users#account"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
  :passwords => "users/passwords", :registrations => "users/registrations",
  :sessions => "users/sessions" }

  resources :users, path: "u" do
    # get :id
  end

  get 'projects/:code-:slug', to: "projects#repo", as: :repo

  # get ':name', to: "developers#show", as: :show_developer
end

app/controllers/panel/catalogs_controller.rb
class Panel::CatalogsController < Panel::PanelController
  before_action :set_panel_catalog, only: [:show, :edit, :update, :destroy]


  def search
    @panel_catalogs = ::Catalog.all.order(id: :desc).page(params[:page])

    if params[:top_catalog].present?
      @panel_catalogs = @panel_catalogs.where(type: params[:top_catalog])
    end

    if params[:name].present?
      @panel_catalogs = @panel_catalogs.where("name LIKE ?", "%#{params[:name]}%")
    end

    if params[:status].present?
      @panel_catalogs = @panel_catalogs.where(status: params[:status])
    end

    if params[:categories_count].present?
      @panel_catalogs = @panel_catalogs.where(categories_count: params[:categories_count])
    end

    render :index
  end

  # GET /panel/catalogs
  def index
    @panel_catalogs = ::Catalog.all.order(id: :desc).page(params[:page])
  end

  # GET /panel/catalogs/1
  def show
  end

  # GET /panel/catalogs/new
  def new
    @panel_catalog = ::Catalog.new
  end

  # GET /panel/catalogs/1/edit
  def edit
  end

  # POST /panel/catalogs
  def create
    @panel_catalog = ::Catalog.new(panel_catalog_params)

    respond_to do |format|
      if @panel_catalog.save
        format.html { redirect_to panel_catalog_path(@panel_catalog), notice: 'Catalog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /panel/catalogs/1
  def update
    respond_to do |format|
      if @panel_catalog.update(panel_catalog_params)
        format.html { redirect_to edit_panel_catalog_url(@panel_catalog), notice: 'Catalog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /panel/catalogs/1
  def destroy
    @panel_catalog.destroy
    respond_to do |format|
      format.html { redirect_to panel_catalogs_url, notice: 'Catalog was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel_catalog
      @panel_catalog = ::Catalog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panel_catalog_params
      params.fetch(:catalog, {}).permit(:name, :slug, :type, :sketch, :footnote)
    end
end

app/controllers/panel/categories_controller.rb
class Panel::CategoriesController < Panel::PanelController
  before_action :set_panel_category, only: [:show, :edit, :update, :destroy, :create_projects]

  def create_projects
    if params[:projects_source_code].blank?
      return false
    end

    projects_source_code = params[:projects_source_code].split(/\r\n|\s/).delete_if{|x| x.blank? || !(x =~ /github\.com/)}

    catalog = @panel_category.catalog
    if catalog.present?
      identity = catalog.project_identity
    end

    projects_source_code.each do |link|
      delay = rand(1..60)
      Project.delay_for(delay).get_and_create_gem_project_from_option({'source_code' => link, 'identity' => identity, category_id: @panel_category.id})
    end

    redirect_to panel_category_url(@panel_category), notice: '正在抓取项目到此类目，请稍等。'
  end

  def search
    @panel_categories = ::Category.all.order(id: :desc).includes(:catalog).page(params[:page])

    if params[:top_catalog].present?
      @panel_categories = @panel_categories.joins(:catalog).where(catalogs: {type: params[:top_catalog]})
    end

    if params[:name].present?
      @panel_categories = @panel_categories.joins(:catalog).where("catalogs.name LIKE ? OR categories.name LIKE ?", "%#{params[:name]}%", "%#{params[:name]}%")
    end

    if params[:status].present?
      @panel_categories = @panel_categories.where(status: params[:status])
    end

    if params[:projects_count].present?
      @panel_categories = @panel_categories.where(projects_count: params[:projects_count])
    end

    render :index
  end

  # GET /panel/categories
  def index
    @panel_categories = ::Category.all.order(id: :desc).includes(:catalog).page(params[:page])
  end

  # GET /panel/categories/1
  def show
    @projects = @panel_category.projects.order(popularity: :desc).page(params[:page])
  end

  # GET /panel/categories/new
  def new
    @panel_category = ::Category.new
  end

  # GET /panel/categories/1/edit
  def edit
  end

  # POST /panel/categories
  def create
    @panel_category = ::Category.new(panel_category_params)
    respond_to do |format|
      if @panel_category.save
        format.html { redirect_to edit_panel_category_url(@panel_category), notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /panel/categories/1
  def update
    respond_to do |format|
      if @panel_category.update(panel_category_params)
        format.html { redirect_to edit_panel_category_url(@panel_category), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /panel/categories/1
  def destroy
    @panel_category.destroy
    respond_to do |format|
      format.html { redirect_to panel_categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel_category
      @panel_category = ::Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panel_category_params
      params.fetch(:category, {}).permit(:name, :status, :slug, :catalog_id)
    end
end

app/controllers/panel/episodes_controller.rb
class Panel::EpisodesController < Panel::PanelController
  before_action :set_panel_episode, only: [:show, :edit, :update, :destroy]

  # GET /panel/episodes
  def index
    @panel_episodes = ::Episode.order(id: :desc).page(params[:page])
  end

  # GET /panel/episodes/1
  def show
    @projects = @panel_episode.projects
  end

  # GET /panel/episodes/new
  def new
    @panel_episode = ::Episode.new
  end

  # GET /panel/episodes/1/edit
  def edit
  end

  # POST /panel/episodes
  def create
    @panel_episode = ::Episode.new(panel_episode_params)

    respond_to do |format|
      if @panel_episode.save!
        format.html { redirect_to panel_episode_path(@panel_episode), notice: 'Episode was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /panel/episodes/1
  def update
    respond_to do |format|
      if @panel_episode.update(panel_episode_params)
        format.html { redirect_to panel_episode_path(@panel_episode), notice: 'Episode was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /panel/episodes/1
  def destroy
    @panel_episode.destroy
    respond_to do |format|
      format.html { redirect_to panel_episodes_url, notice: 'Episode was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel_episode
      @panel_episode = ::Episode.find_by(human_id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panel_episode_params
      params.fetch(:episode, {}).permit(:human_id, :project_list, :status, :recommend_at)
    end
end

app/controllers/panel/panel_controller.rb
class Panel::PanelController < ApplicationController
  layout 'panel'
end

app/controllers/panel/projects_controller.rb
class Panel::ProjectsController < Panel::PanelController
  before_action :set_panel_project, only: [:show, :edit, :update, :destroy]

  def magic_search
  end

  def search_result
    if params[:projects_source_code].blank?
      return false
    end

    projects_source_code = params[:projects_source_code].split(/\r\n|\s/).delete_if{|x| x.blank? || !(x =~ /github\.com/)}

    # 
    @panel_projects = Project.where(source_code: projects_source_code).order(id: :desc).includes(:category).page(params[:page])
    render :index
  end


  def search
    @panel_projects = ::Project.all.order(id: :desc).includes(:category).page(params[:page])

    if params[:name].present?
      @panel_projects = @panel_projects.joins(:category).where("projects.name LIKE ? OR categories.name LIKE ?", "%#{params[:name]}%", "%#{params[:name]}%")
    end

    if params[:status].present?
      @panel_projects = @panel_projects.where(status: params[:status])
    end

    if params[:identity].present?
      @panel_projects = @panel_projects.where(identity: params[:identity])
    end

    render :index
  end

  # GET /panel/projects
  def index
    @panel_projects = ::Project.all.includes(:category).page(params[:page])
  end

  # GET /panel/projects/1
  def show
  end

  # GET /panel/projects/new
  def new
    @panel_project = ::Project.new
  end

  # GET /panel/projects/1/edit
  def edit
  end

  # POST /panel/projects
  def create
    @panel_project = ::Project.new(panel_project_params)

    respond_to do |format|
      if @panel_project.save
        format.html { redirect_to edit_panel_project_url(@panel_project), notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /panel/projects/1
  def update
    respond_to do |format|
      if @panel_project.update(panel_project_params)
        format.html { redirect_to edit_panel_project_url(@panel_project), notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /panel/projects/1
  def destroy
    @panel_project.destroy
    respond_to do |format|
      format.html { redirect_to panel_projects_url, notice: 'Project was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel_project
      @panel_project = ::Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panel_project_params
      params.fetch(:project, {}).permit(:author, :name, :human_name, :identity,
        :status, :source_code, :description, :today_recommend, :given_name,
        :category_id)
    end
end

app/controllers/panel/stats_controller.rb
class Panel::StatsController < Panel::PanelController
  def index
  end
end

app/helpers/panel/stats_helper.rb
module Panel::StatsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def active_tab(options)
    if current_page?(options)
      'active'
    end
  end
end

app/views/panel/projects/_form.html.erb
<% if panel_project.new_record? %>
  <% url = panel_projects_path %>
<% else %>
  <% url = panel_project_path(panel_project) %>
<% end %>

<%= form_for panel_project, url: url do |f| %>
  <% if panel_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(panel_project.errors.count, "error") %> prohibited this panel_project from being saved:</h2>

      <ul>
      <% panel_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control", disabled: !panel_project.new_record? %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", disabled: !panel_project.new_record? %>
  </div>

  <div class="form-group">
    <%= f.label :source_code %>

    <% if panel_project.source_code.present? %>
      <small>
        <%= link_to panel_project.source_code, target: "_blank" do %>
          <i class="fa fa-globe"></i>
        <% end %>
      </small>
    <% end %>

    <%= f.text_field :source_code, class: "form-control", disabled: !panel_project.new_record?, required: true %>
  </div>

  <div class="form-group">
    <%= f.label :human_name %>
    <%= f.text_field :human_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :identity %>
    <%= f.select :identity, options_for_select(Project.identities.keys, panel_project.identity), {include_blank: true}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, options_for_select(Project.statuses.keys, panel_project.status), {include_blank: true}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: 3 %>
  </div>

  <div class="form-group">
    <%= f.label :today_recommend do %>
      <%= f.check_box :today_recommend %> 今日推荐？
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :given_name %>
    <%= f.text_field :given_name, class: "form-control" %>

    <p class="help-block">某些 gem 在 GitHub 上的 Repo 项目名与在 rubygems.org 上不一致，导致下载失败，可用此修复。</p>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.select :category_id, Category.all.includes(:catalog).collect { |p| [ p.full_name, p.id ] }, {include_blank: true}, class: "form-control select2" %>
  </div>

  <div class="actions">
    <%= f.submit "提交项目", class: "btn btn-primary", data: {disable_with: "正在提交"} %>
  </div>
<% end %>

app/views/panel/projects/_item_tbody.html.erb
<tr>
  <td><%= project.author %></td>
  <td><%= link_to project.name, panel_project_path(project) %></td>
  <td><%= project.identity %></td>
  <td><%= project.status %></td>
  <td><%= project.github_info.present? %></td>
  <td><%= project.relate_info.present? %></td>
  <td><%= link_to 'Edit', edit_panel_project_path(project), target: "_blank" %></td>
  <td><%= link_to 'Destroy', panel_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <td><%= link_to '前台', project, target: "_blank" %></td>
  <td><%= link_to '后台', rails_admin.show_path('Project', project), target: "_blank" %></td>
</tr>

app/views/panel/projects/_item_thead.html.erb
<tr>
  <th>项目作者</th>
  <th>项目名</th>
  <th>Identity</th>
  <th>Status</th>
  <th>Github</th>
  <th>Info</th>
  <th colspan="3"></th>
</tr>

app/views/panel/projects/_tbody.html.erb
<tr>
  <td><%= panel_project.author %></td>
  <td><%= link_to panel_project.name, panel_project_path(panel_project), target: "_blank" %></td>
  <td><%= panel_project.status %></td>
  <td><%= panel_project.source_code %></td>

  <td>
    <% if panel_project.category.present? %>
      <%= link_to panel_project.category.name, panel_category_path(panel_project.category), target: "_blank" %>
    <% end %>
  </td>

  <td></td>
  <td></td>

  <!-- <td><%#= link_to 'Show', panel_project_path(panel_project), target: "_blank" %></td> -->
  <td><%= link_to 'Edit', edit_panel_project_path(panel_project), target: "_blank" %></td>
  <td><%= link_to 'Destroy', panel_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <td><%= link_to "前台", project_path(panel_project), target: "_blank" %></td>
  <td><%= link_to "后台", rails_admin.show_path('Project', panel_project), target: "_blank" %></td>
</tr>

app/views/panel/projects/_thead.html.erb
<tr>
  <th>Author</th>
  <th>Name</th>
  <th>Status</th>
  <th>Github</th>
  <th>Category</th>
  <th>GithubInfo</th>
  <th>RelateInfo</th>
  <th colspan="4"></th>
</tr>

app/views/panel/projects/edit.html.erb
<h1>
  <%= @panel_project.name %>

  <small><%= link_to 'Show', @panel_project %></small>
  <small class="pull-right">
    <%= link_to 'Back', search_panel_projects_path(name: @panel_project.name) %>
  </small>
</h1>

<%= render 'form', panel_project: @panel_project %>

app/views/panel/projects/index.html.erb
<h1>
  Panel Projects

  <small>
    <%= link_to 'New Panel Project', new_panel_project_path %>

    <%= link_to 'Magic Search', magic_search_panel_projects_path %>
  </small>
</h1>



<%= form_tag search_panel_projects_path, method: :get, class: "form-inline" do %>
  <div class="form-group">
    <%= label_tag :name, "Name" %>
    <%= text_field_tag :name, params[:name], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :status %>
    <%= select_tag :status, options_for_select(Project.statuses.keys, params[:status]), include_blank: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :identity %>
    <%= select_tag :identity, options_for_select(Project.identities.keys, params[:identity]), include_blank: true, class: "form-control" %>
  </div>

  <%= submit_tag "搜索", class: "btn btn-default", data: {disable_with: "正在搜索"} %>
<% end %>


<table class="table table-striped">
  <thead>
    <%= render "panel/projects/thead" %>
  </thead>

  <tbody>
    <% @panel_projects.each do |panel_project| %>
      <%= render "panel/projects/tbody", panel_project: panel_project %>
    <% end %>
  </tbody>
</table>

<%= magic_paginate @panel_projects %>

app/views/panel/projects/magic_search.html.erb
<%= form_tag search_result_panel_projects_path, :class => "form" do %>
  <div class="form-group">
    <%= label_tag :projects_source_code %>
    <%= text_area_tag :projects_source_code, params[:projects_source_code], class: "form-control", rows: 15 %>
  </div>

  <button type="submit" class="btn btn-default">Submit</button>
<% end %>

app/views/panel/projects/new.html.erb
<h1>
  New Panel Project

  <small class="pull-right">
    <%= link_to 'Back', panel_projects_path %>
  </small>
</h1>

<%= render 'form', panel_project: @panel_project %>

app/views/panel/projects/show.html.erb
<h1>
  <%= @panel_project.name %>

  <small>
    <%= link_to 'Edit', edit_panel_project_path(@panel_project) %>
  </small>

  <small class="pull-right">
    <%= link_to 'Back', panel_projects_path %>
  </small>
</h1>

<table class="table table-striped">
  <thead>
    <%= render "panel/projects/thead" %>
  </thead>

  <tbody>
    <%= render "panel/projects/tbody", panel_project: @panel_project %>
  </tbody>
</table>

<div class="panel panel-default">
  <div class="panel-heading">
    Description
  </div>

  <div class="panel-body">
    <%= simple_format @panel_project.description %>
  </div>
</div>