config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :article_catalogs
  resources :article_categories, path: "go"
  resources :sites, path: "site"
  # get 'quickrank_performances/index'

  # get 'quickrank_portfolios/index'

  # get 'quickrank_snapshots/index'

  get :search, to: "pages#search"

  resources :fundcompany, path: 'company', only: [] do
    collection do
      get :star
      get :best_return
      get :performance
    end
  end

  resources :quickrank do
    collection do
      # get ":date_history", to: "quickrank#date_history", as: :date_history

      get :performance, to: "quickrank_performances#index"
      get :portfolio, to: "quickrank_portfolios#index"
      get :snapshot, to: "quickrank_snapshots#index"
      get :history, to: "fund_rankings#index"

      get :search
      post :search
    end
  end

  get "quickrank/history/search", to: "fund_rankings#search"

  resources :tags, path: 'tag', only: [:index, :show]

  resources :fund_yields
  resources :task_logs
  resources :fund_rankings
  resources :stocks
  resources :quotes


  resources :fund_fen_hongs do
    collection do
      get :list
    end
  end

  resources :fund_chai_fens


  mount RedactorRails::Engine => '/redactor_rails'

  resources :articles do
    resources :comments

    resources :agreement_articles, only: [:create, :destroy]
  end

  resources :index_reports, only: :index do
    collection do
      get ":catalog_slug", to: "index_reports#catalog", as: :catalog_slug
      get ":catalog_slug/:category_slug", to: "index_reports#category", as: :catalog_slug_category_slug
    end
  end

  resources :index_reports, path: 'index_report'

  # resources :index_catalogs
  # resources :index_categories

  get 'user_favor_comment/create'

  get 'user_favor_comment/destroy'

  get 'pages/:name', to: "pages#show"

  mount RuCaptcha::Engine => "/rucaptcha"

  authenticate :user, lambda { |u| u.is_admin? } do
    namespace :panel do
      resources :stats

      resources :episodes

      resources :categories do
        member do
          post :create_projects
        end

        collection do
          get :search
        end
      end
      resources :catalogs do
        collection do
          get :search
        end
      end
      resources :projects do
        collection do
          get :search
          get :magic_search
          post :search_result
        end
      end
    end
  end

  resources :episodes do
    collection do
      # get 'today-recommends', to: "episodes#today", as: :today
      get :today
    end
  end
  # resources :developers, only: [:show]
  resources :developers, path: "manager"

  resources :net_worths

  resources :user_recommend_projects, only: [:create, :destroy]
  resources :user_star_projects, only: [:create, :destroy]
  resources :comments

  authenticate :user, lambda { |u| u.is_admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :projects, path: "fund" do
    member do
      get :popularity, to: "repos#popularity"

      get :star, to: "repos#star"
      get :recommend, to: "repos#recommend"

      get :calculus, to: "project_arithmetic#calculus"

      get :managers

      get :distribute
    end

    resource :recommend_project, only: [:new, :create] do
      member do
        post 'add_to_episode/:episode_id', action: :add, as: :add_to
        delete 'remove_from_episode/:episode_id', action: :remove, as: :remove_from
      end
    end

    post :star, to: "user_star_projects#create"
    post :recommend, to: "user_recommend_projects#create"

    delete :star, to: "user_star_projects#destroy"
    delete :recommend, to: "user_recommend_projects#destroy"

    collection do
      get :search, to: "project_search#index"
      get :ruby_gems, to: "project_search#index", type: 'gemspec', as: :search_gem
      get :php_packages, to: "project_search#index", type: 'package', as: :search_package
      get :swift_pods, to: "project_search#index", type: 'pod', as: :search_pod
    end

    resources :comments
  end

  resources :developer_projects, only: [:destroy]

  get ':author/:name/star', to: "repos#star", as: :star_repo
  get ':author/:name/recommend', to: "repos#recommend", as: :recommend_repo
  get ':author/:name/popularity', to: "repos#popularity", as: :popularity_repo


  resources :catalogs, path: "company" do
    resources :catalog_developers, path: 'managers', only: [:index]
  end
  resources :categories

  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'ruby-gems', to: "catalogs#rails", as: :rails
  get 'Ruby-Gems', to: "catalogs#rails"
  get 'gems', to: "catalogs#rails"
  get 'swift-pods', to: "catalogs#swift", as: :swift
  get 'Swift-Pods', to: "catalogs#swift"
  get 'pods', to: "catalogs#swift"
  get 'PHP-Packages', to: "catalogs#laravel", as: :laravel
  get 'packages', to: "catalogs#laravel"

  get 'account', to: "users#account"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
  :passwords => "users/passwords", :registrations => "users/registrations",
  :sessions => "users/sessions" }

  resources :users, path: "u" do
    # get :id
  end

  get 'projects/:code-:slug', to: "projects#repo", as: :repo

  # get ':name', to: "developers#show", as: :show_developer
end

app/models/article_category.rb
# == Schema Information
#
# Table name: article_categories
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  slug               :string(255)
#  cover              :string(255)
#  intro              :string(255)
#  article_catalog_id :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  articles_count     :integer          default(0), not null
#  top_at             :datetime
#

class ArticleCategory < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name, scope: :article_catalog_id

  before_validation :set_slug

  has_many :articles
  belongs_to :article_catalog

  def set_slug
    if self.name.present?
      self.slug ||= Pinyin.t(self.name, splitter: "").parameterize
    end
  end

  def self.init_datas
    [%W(分享与探索 问与答    分享发现    分享创造    分享邀请码    自言自语    奇思妙想    随想    设计    Blog   ),
    %W(V2EX  V2EX    Project    DNS    反馈    GAE    使用指南   ),
    %W(iOS iDev    iCode    iMarketing    iAd    iTransfer),
    %W(Geek  程序员    Python    Android    Linux    宽带症候群    PHP    云计算    外包    硬件    Java    服务器    MySQL    Bitcoin    Linode    编程    设计师    汽车    Kindle    Markdown    Tornado    MongoDB    Rails    Redis    字体排印    Ruby    商业模式    数学    Photoshop    LEGO    SONY    自然语言处理),
    %W(Apple macOS    iPhone    MacBook    iPad        配件        iMac    Mac    iPod        MobileMe    iWork    iLife    GarageBand),
    %W(生活  二手交易    酷工作    天黑以后    免费赠送    音乐    电影    物物交换    剧集    信用卡    美酒与美食    团购    投资    旅行    阅读    摄影    绿茵场    Baby    宠物    咖啡    乐活    骑行    非诚勿扰    日记    植物    蘑菇    行程控),
    %W(Internet  Google    Twitter    Coding    Facebook    Wikipedia    reddit),
    %W(城市  北京    上海    深圳    杭州    成都    广州    武汉    昆明    天津   青岛),
    %W(品牌  UNIQLO    Lamy    宜家    无印良品    Gap    Nike    Moleskine    Adidas    G-Star)].each do |catalog_with_array|
      catalog_name = catalog_with_array[0]
      catalog = ArticleCatalog.find_by(name: catalog_name)

      catalog_with_array.each_with_index do |category_name, index|
        if index.zero?
          next
        else
          catalog.article_categories.create(name: category_name)
        end
      end
    end
  end

  def to_param
    self.slug
  end

  def parent_name
    self.article_catalog.name
  end

  def self.select_container
    self.all.includes(:article_catalog).map{|x| ["#{x.parent_name}/#{x.name}", x.id]}
  end
end

app/controllers/article_categories_controller.rb
class ArticleCategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :set_article_category, only: [:show, :edit, :update, :destroy]

  # GET /article_categories
  # GET /article_categories.json
  def index
    @article_categories = ArticleCategory.all
  end

  # GET /article_categories/1
  # GET /article_categories/1.json
  def show
  end

  # GET /article_categories/new
  def new
    @article_category = ArticleCategory.new
  end

  # GET /article_categories/1/edit
  def edit
  end

  # POST /article_categories
  # POST /article_categories.json
  def create
    @article_category = ArticleCategory.new(article_category_params)

    respond_to do |format|
      if @article_category.save
        format.html { redirect_to @article_category, notice: 'Article category was successfully created.' }
        format.json { render :show, status: :created, location: @article_category }
      else
        format.html { render :new }
        format.json { render json: @article_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_categories/1
  # PATCH/PUT /article_categories/1.json
  def update
    respond_to do |format|
      if @article_category.update(article_category_params)
        format.html { redirect_to @article_category, notice: 'Article category was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_category }
      else
        format.html { render :edit }
        format.json { render json: @article_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_categories/1
  # DELETE /article_categories/1.json
  def destroy
    @article_category.destroy
    respond_to do |format|
      format.html { redirect_to article_categories_url, notice: 'Article category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_category
      @article_category = ArticleCategory.find_by(slug: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_category_params
      params.require(:article_category).permit(:name, :slug, :cover, :intro, :article_catalog_id)
    end
end

app/helpers/article_categories_helper.rb
module ArticleCategoriesHelper
end

app/views/article_categories/_form.html.erb
<%= form_for(article_category) do |f| %>
  <% if article_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article_category.errors.count, "error") %> prohibited this article_category from being saved:</h2>

      <ul>
      <% article_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div class="field">
    <%= f.label :cover %>
    <%= f.text_field :cover %>
  </div>

  <div class="field">
    <%= f.label :intro %>
    <%= f.text_field :intro %>
  </div>

  <div class="field">
    <%= f.label :article_catalog_id %>
    <%= f.number_field :article_catalog_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/article_categories/edit.html.erb
<h1>Editing Article Category</h1>

<%= render 'form', article_category: @article_category %>

<%= link_to 'Show', @article_category %> |
<%= link_to 'Back', article_categories_path %>

app/views/article_categories/index.html.erb
<div class="container">
  <h1>Article Categories</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Slug</th>
        <th>Cover</th>
        <th>Intro</th>
        <th>Article catalog</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @article_categories.each do |article_category| %>
        <tr>
          <td><%= article_category.name %></td>
          <td><%= article_category.slug %></td>
          <td><%= article_category.cover %></td>
          <td><%= article_category.intro %></td>
          <td><%= article_category.article_catalog_id %></td>
          <td><%= link_to 'Show', article_category %></td>
          <td><%= link_to 'Edit', edit_article_category_path(article_category) %></td>
          <td><%= link_to 'Destroy', article_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Article Category', new_article_category_path %>
</div>

app/views/article_categories/new.html.erb
<h1>New Article Category</h1>

<%= render 'form', article_category: @article_category %>

<%= link_to 'Back', article_categories_path %>

app/views/article_categories/show.html.erb
<% set_meta_tags title: @article_category.name %>

<div class="container content">
  <p>
    <strong>Name:</strong>
    <%= @article_category.name %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= @article_category.slug %>
  </p>

  <p>
    <strong>Cover:</strong>
    <%= @article_category.cover %>
  </p>

  <p>
    <strong>Intro:</strong>
    <%= @article_category.intro %>
  </p>

  <p>
    <strong>Article catalog:</strong>
    <%= @article_category.article_catalog_id %>
  </p>

  <%= link_to 'Edit', edit_article_category_path(@article_category) %> |
  <%= link_to 'Back', article_categories_path %>
</div>